name: ${project.name}
main: studio.magemonkey.fabled.enchants.FabledEnchants
version: ${project.version}
depend: [ Codex ]
softdepend: [ Fabled ]
api-version: 1.16
authors: [ Eniripsa96, Sentropic ]

permissions:
  fabledenchants.list:
    description: basic list of enchantments
    default: true
  fabledenchants.book:
    description: gives a book with enchantment descriptions
    default: true
  fabledenchants.admin:
    description: applying enchantments
    default: op
  fabledenchants.table:
    description: getting custom enchantments from the table
    default: true
  fabledenchants.enchant:
    description: access to all enchantments
    default: true
  fabledenchants.enchant.vanilla:
    description: access to all vanilla enchantments
    default: true